### ISSUE TITLE
request feature

### ISSUE THREAD

**Issue by higi** [Zendrex/ARK-Linux-Server-Script#15]
can u please add renice -20 whole server process including all threads 

something like
renice -n -20 -p `ps --no-heading -Lo tid PID`

**Comment by higi** [comment]
and hows going work on?)
Server automatic updater.
Update checker
update installer

THX

**Comment by Zendrex** [comment]
Im currently not home, however I will add it as a requested feature. I personally am not very familiar with renice so I will have to do some researching. If you however know the standard for it, feel free to fork and add the additions yourself!

**Comment by Zendrex** [comment]
Woops, didnt mean to close it.

**Comment by Zendrex** [comment]
Due to how our script is being developer, we wont currently be adding renice, however the updater/installer are in. Closed
