### ISSUE TITLE
RCon Support

### ISSUE THREAD

**Issue by darkcloud784** [Zendrex/ARK-Linux-Server-Script#20]
Please add in variables for RCon Port and startup. Would also be nice if the script installed as a service and didn't have to spit out checks for each command used.

**Comment by Zendrex** [comment]
We will add RCON, current I am having some real world issues to deal with so this may be delayed to next week if ComputerBear doesnt want to make it.

**Comment by Zendrex** [comment]
I have yet to test rcon support for ark, if someone can and post their results, would be great.

**Comment by Zendrex** [comment]
RCON seems to work, closing.
