### ISSUE TITLE
Parameters Default Bug

### ISSUE THREAD

**Issue by ComputerBaer** [Zendrex/ARK-Linux-Server-Script#21]
We need to send all parameters on startup, also the defaults.

If a parameter changed, the server started and set back to default later, the server will always start with the old changed value and not with the default. The server saves all modified settings to GameUserSettings.ini and load it from there if it not passed as parameter.

Deleting the GameUserSettings.ini is not an option.

**Comment by Zendrex** [comment]
I believe this is to be an issue with the server code then. Its standard to run the params before checking for old information. What we could do then is make is so instead of checking every param, simply printf them to the GameUserSettings.ini on every start. Would be a bit tricky but doable.

**Comment by ComputerBaer** [comment]
Or we do not remove defaults from $executeString (paramters_check), that is simple and would work.

I am planning to add a value check for all parameters. NumberParameters can only contain numbers and not "potato", BooleansParameters can only contain true/false.

**Comment by Zendrex** [comment]
sounds good
