### ISSUE TITLE
Need to be root to run the script?

### ISSUE THREAD

**Issue by salamanderrake** [Zendrex/ARK-Linux-Server-Script#22]
Do I need to be root to run the script, it fails with the iptables commands, maybe you should separate that part out of the script so we don't need to run it with sudo/or as root.

**Comment by salamanderrake** [comment]
Never mind I just added the ports to my firewalld config

**Comment by Zendrex** [comment]
We are going to chance it so its under sudo in a upcoming update. Right now we are focusing on our auto-updater.

**Comment by salamanderrake** [comment]
ok thanks

**Comment by noxturno** [comment]
quick question , I need to edit de sh before running it right?

**Comment by Zendrex** [comment]
You only need to edit the config file.

**Comment by ComputerBaer** [comment]
The [new version of this script](https://github.com/ComputerBaer/ARK-Linux-Server-Script-v2) can be executed as any user. Only the ````dependencies.sh```` needs root permissions.
