### ISSUE TITLE
Server Stopped working after update

### ISSUE THREAD

**Issue by svetty** [Zendrex/ARK-Linux-Server-Script#30]
After i updated to your latest script version server no longer works for me.
everything launches just fine, checked with htop and just as the CPU load goes down (when its supposed to be online) it just shuts down instead.

I've tested making a start file, and that one worked just fine.

./ShooterGameServer TheIsland?listen?SessionName=Severname?ServerAdminPassword=Adminpassword? -server -log

**Comment by Zendrex** [comment]
The server never actually turns on?

**Comment by svetty** [comment]
Nope, it usually takes 3min for the server to start. CPU load and everything drops down at around that time but server never shows online, and a few mins later it the process is gone.

**Comment by Zendrex** [comment]
Add me on steam: im_not_zendrex

**Comment by Zendrex** [comment]
Sorry, fixed it my steam name.
its imnotzendrex

**Comment by svetty** [comment]
added

**Comment by Zendrex** [comment]
Possible int error on startup with some versions of Ubuntu
