### ISSUE TITLE
Server starting fails..

### ISSUE THREAD

**Issue by ESnowden** [Zendrex/ARK-Linux-Server-Script#31]
The script has worked for me just fine in the past. Upon updating the script and re-configuring the configuration.ini file issues occur.

Script is run as followed on a normal user on Ubuntu 14.04 server : sudo ./arkserver.sh start
Here is the output after executing the start command. 

```
To view server settings, use: ./arkserver.sh status

 Now executing....
 Checking parameters.
parameters_check: line 266: [: too many arguments
parameters_check: line 269: [: too many arguments
 Check complete, starting server compiling.

 Executing commandline in screen session named: ArkServer

 Server is starting up. To access the console, relaunch the script and use: ./arkserver.sh view
```

I have attempted to modify my configuration file, this had no impact on the issue.

**Comment by Zendrex** [comment]
can you add me on steam, its 'imnotzendrex'

**Comment by ESnowden** [comment]
Added: Steam name is Apothecarium of the UnderRock

**Comment by Zendrex** [comment]
Resolved (caused by error whenupdating the game server)
