### ISSUE TITLE
Append previous config settings

### ISSUE THREAD

**Issue by darkcloud784** [Zendrex/ARK-Linux-Server-Script#33]
Would be nice to not have to re-do my config every single time this script is updated. I know that the devs of the game mess with the configs but there should be a way to append the config settings that don't need to be changed to the new config.

**Comment by Zendrex** [comment]
I was thinking about this, and I will look into getting some concept for it. I'm still learning a bit out adding new sections to the config (wherever i desire) without having to reset the config every time.

**Comment by Grimstout** [comment]
Do you really have to have the configuration.ini file since we have the gameusersettings.ini file? If so, could we have it install initially then never check again, which would not have it change the settings.

**Comment by ComputerBaer** [comment]
The [new version of this script](https://github.com/ComputerBaer/ARK-Linux-Server-Script-v2) doesn't update your configuration file.
