### ISSUE TITLE
What does this mean ?

### ISSUE THREAD

**Issue by noxturno** [Zendrex/ARK-Linux-Server-Script#34]
4.5.1-0+UE4 7038 3077 402 4
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3155) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015

**Comment by noxturno** [comment]
changed the ports and still get 
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by Zendrex** [comment]
````[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.````
This is normal for linux. Server startup times usually take a couple minutes depending on your server.

**Comment by noxturno** [comment]
how long should I let it run ?before I think is dead

**Comment by Zendrex** [comment]
Yes, the SteamAPI error means nothing, as long as in the console it says "port binded" or something similar you should be good.

**Comment by Zendrex** [comment]
Sorry, didnt mean to close it.

**Comment by noxturno** [comment]
is fine !! since I didnt see no output of data on the console I though it wasnt running xD seems to be running GREAT
