### ISSUE TITLE
Fail to launch ARK server

### ISSUE THREAD

**Issue by DarkMilou** [Zendrex/ARK-Linux-Server-Script#41]
Hello, I have a error when launch ARK server, on putty it write : 
[ .... ] Starting ark-server: arkserversession not found: ark-server
[ FAIL ] Starting ark-server: Unable to start arkserver

**Comment by ComputerBaer** [comment]
Are you sure, that you use this script?
We have no output like this: `[ FAIL ] Starting ark-server: Unable to start arkserver`

I have created a test server and it works.

**Comment by Zendrex** [comment]
That is issues via the ark server file management system. Try saving a backup of your world and reinstalling the game server and try again.
