### ISSUE TITLE
Work with us?

### ISSUE THREAD

**Issue by FezVrasta** [Zendrex/ARK-Linux-Server-Script#8]
We have the same project on GitHub:

https://github.com/FezVrasta/ark-server-tools

We support lot of features and we have already daemons for almost every distro.
I think you may contribute to our project instead of do the same stuff here.

Greetings,
Fez.

**Comment by Zendrex** [comment]
Thanks for the offer, but I honestly did my script to learn more then anything. I actually used your script when the linux files dropped and I never got the daemon to work with the manager, thus why I made my own. I would be glad to give some input, but I would like to stick to my own for learning purposes.

Ps, I am interested how to did the updater for the gameserver. Cudos for figuring that one out.

-Zendrex

**Comment by FezVrasta** [comment]
The daemons will be released with 1.1 soon

**Comment by Zendrex** [comment]
Whats the general idea behind you guys checking steam for a newer version of the server files?

**Comment by FezVrasta** [comment]
Sorry I don't get what you mean. :(

**Comment by Zendrex** [comment]
You guys claim to have a game server updater. Im curious how you guys do this.

**Comment by FezVrasta** [comment]
The entire source code is there, just look at the function.

**Comment by Zendrex** [comment]
We figured it out and are implementing it soon.

**Comment by FezVrasta** [comment]
I don't see why you are working on this project while our project has already all these features, you may just contribute to our. No reason to work on two different projects.

Both are open sources.

**Comment by FezVrasta** [comment]
Ah sorry, I didn't see your project is not open source :/ that sucks. Thanks anyway

**Comment by Zendrex** [comment]
It actually is, when I originally made this however I never actually put a license file on it. Thankyou for reminding me about it. :)

Also, the reason why I decide to work on this is due to me wanting to learn from self experience. Your guy's tool is great, but I kinda wanted to make something on my own for learning purposes.

**Comment by FezVrasta** [comment]
@Zendrex actually you can put every configuration options of the server inside the configuration of our tool. so I don't get where is the problem.
