### ISSUE TITLE
Error when update

### ISSUE THREAD

**Issue by super54** [Zendrex/ARK-Linux-Server-Script#9]
Hi,

I have a problem when i run update command : 

Redirecting stderr to '/root/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API.../home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp (3030) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp (3030) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp (3181) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
/home/buildbot/buildslave/steam_rel_client_linux/build/src/steamconsole/../common/steam/client_api.cpp (393) : Assertion Failed: ClientAPI_Init(GlobalInstance): GetIClientRemoteControlManager returned NULL.
FAILED.

You have some ideas ?

**Comment by Zendrex** [comment]
Are you running it as root? This usually occurs if you try it on a user other then root. (steam api issue)

**Comment by super54** [comment]
Yes it's OK.

This error appear when i am in root user.

thanks for help

**Comment by Zendrex** [comment]
I suggest re downloading the script as well. I updated it with an auto-updater (script wise) so no need for doing manual patches.

**Comment by super54** [comment]
Yes it's OK when i run in no root user ;)
